# Generated by Django 3.2.7 on 2021-09-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_telegroup_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
