# Generated by Django 3.2.7 on 2021-10-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=120, null=True),
        ),
    ]
